### ISSUE TITLE
Error: str_contains(): Passing null to parameter #1 ($haystack) of type string is deprecated

### ISSUE THREAD

**Issue by Matoseb** [visionbites/kirby-usage-reference#1]
When creating a new page with `redirect: false`. I get the error message `str_contains(): Passing null...`

PHP Version: 8.2

Here is the page blueprint:
```yml
title: Tag
icon: tag

create:
  status: listed
  slug: "{{ page.title }}"
  redirect: false

options:
  changeStatus: false
  changeSlug: false
  move: false
  preview: false

sections:
  fields:
    fields:
      content:
        label: Found in pages
        type: headline
      gap:
        type: gap
  references:
    headline: References to this page
    # template: usageReference
    type: usageReference
```

Here is a fix at `usage-reference/Services/ReferenceService.php:53`
```php

$maskedUuid = str_replace('/', '\/', $uuid);

// fix
if (is_null($datum)) continue;

if (str_contains($datum, $uuid) || str_contains($datum, $maskedUuid)) {
   $hasMatch = true;
};

```
